//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShifts
    {
        public int shift_id { get; set; }
        public int employee_id { get; set; }
        public int branch_id { get; set; }
        public System.DateTime shift_start { get; set; }
        public Nullable<System.DateTime> shift_end { get; set; }
        public string notes { get; set; }
        public int history_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
