//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.OnlineSaleOffers = new HashSet<OnlineSaleOffers>();
            this.PawnLoanItems = new HashSet<PawnLoanItems>();
            this.PriceHistory = new HashSet<PriceHistory>();
            this.PurchaseContractItems = new HashSet<PurchaseContractItems>();
            this.SalesItems = new HashSet<SalesItems>();
        }
    
        public int item_id { get; set; }
        public string name { get; set; }
        public int category_id { get; set; }
        public string description { get; set; }
        public decimal estimated_value { get; set; }
        public decimal sale_price { get; set; }
        public int condition_id { get; set; }
        public int acquisition_source_type_id { get; set; }
        public Nullable<int> acquisition_source_id { get; set; }
        public Nullable<int> current_branch_id { get; set; }
        public int item_status_id { get; set; }
        public int history_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual AcquisitionSourceTypes AcquisitionSourceTypes { get; set; }
        public virtual Branches Branches { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual ItemConditions ItemConditions { get; set; }
        public virtual RecordHistory RecordHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineSaleOffers> OnlineSaleOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PawnLoanItems> PawnLoanItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceHistory> PriceHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseContractItems> PurchaseContractItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesItems> SalesItems { get; set; }
        public virtual ItemStatuses ItemStatuses { get; set; }
    }
}
