//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineSaleOffers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineSaleOffers()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int online_offer_id { get; set; }
        public int item_id { get; set; }
        public int platform_id { get; set; }
        public string offer_title { get; set; }
        public decimal listing_price { get; set; }
        public System.DateTime listing_date { get; set; }
        public System.DateTime expiration_date { get; set; }
        public string url { get; set; }
        public int status_id { get; set; }
        public Nullable<int> views_count { get; set; }
        public Nullable<int> messages_count { get; set; }
        public string notes { get; set; }
        public bool is_active { get; set; }
        public int history_id { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual OnlinePlatforms OnlinePlatforms { get; set; }
        public virtual RecordHistory RecordHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
