//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PawnShopEntities : DbContext
    {
        public PawnShopEntities()
            : base("name=PawnShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcquisitionSourceTypes> AcquisitionSourceTypes { get; set; }
        public virtual DbSet<AddressSources> AddressSources { get; set; }
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ContractStatuses> ContractStatuses { get; set; }
        public virtual DbSet<DocumentTypes> DocumentTypes { get; set; }
        public virtual DbSet<EmployeeRoles> EmployeeRoles { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeeShifts> EmployeeShifts { get; set; }
        public virtual DbSet<FinalizationSources> FinalizationSources { get; set; }
        public virtual DbSet<InterestRates> InterestRates { get; set; }
        public virtual DbSet<ItemConditions> ItemConditions { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<ItemStatuses> ItemStatuses { get; set; }
        public virtual DbSet<OnlinePlatforms> OnlinePlatforms { get; set; }
        public virtual DbSet<OnlineSaleOffers> OnlineSaleOffers { get; set; }
        public virtual DbSet<PawnLoanItems> PawnLoanItems { get; set; }
        public virtual DbSet<PawnLoans> PawnLoans { get; set; }
        public virtual DbSet<PaymentMethods> PaymentMethods { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<PriceHistory> PriceHistory { get; set; }
        public virtual DbSet<PurchaseContractItems> PurchaseContractItems { get; set; }
        public virtual DbSet<PurchaseContracts> PurchaseContracts { get; set; }
        public virtual DbSet<RecordHistory> RecordHistory { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<SalesItems> SalesItems { get; set; }
        public virtual DbSet<SalesStatuses> SalesStatuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
