//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payments()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int payment_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public decimal amount { get; set; }
        public int payment_method_id { get; set; }
        public string description { get; set; }
        public bool is_active { get; set; }
        public int history_id { get; set; }
    
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual RecordHistory RecordHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
